[project]
name = "chainlit-samples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chainlit>=2.5.5",
    "openai>=1.77.0",
    "pipdeptree>=2.26.1",
    "pydantic-ai-slim[openai]>=0.1.9",
]
